linux: use poky's linux-yocto setup

diff --git a/base/setup-environment b/base/setup-environment
--- a/base/setup-environment
+++ b/base/setup-environment
@@ -19,7 +19,8 @@
 #
 # Add options for the script
 # Copyright (C) 2013 Freescale Semiconductor, Inc.
-CWD=`cd .;pwd`
+
+CWD="`cd .;pwd`"
 PROGNAME=setup-environment
 export BSPDIR="$CWD"
 TEMPLATECONF=${PWD}/layers/meta-karo/base/conf
@@ -50,20 +51,18 @@ directory <build-dir>. The build directory configuration is unchanged.
 
     shopt -q nullglob && nullglob=false || nullglob=true
     $nullglob && shopt -s nullglob
-    for s in layers/*/conf/machine/*.conf;do
-        echo -e "
-Supported machines: `echo; ls layers/*/conf/machine/*.conf | \
+    echo -e "
+Supported machines: `echo; find layers/ -path '*/conf/machine/*.conf' | \
 sed 's:^.*/:\t:;s/\.conf//' | sort`
 
-Supported distros: `echo; ls layers/*/conf/distro/*.conf | \
+Supported distros: `echo; find layers/ -path '*/conf/distro/*.conf' | \
 sed 's:^.*/:\t:;s/\.conf//' | sort`
 
 To build for a machine listed above, run this script as:
 DISTRO=<distro> MACHINE=<machine> source $PROGNAME <build-dir>
 "
-        $nullglob && shopt -u nullglob
-        return
-    done
+    $nullglob && shopt -u nullglob
+    return
     cat << EOF
 No machine configuration files found!
 Make sure, to set up your yocto source directory with:
@@ -120,56 +119,61 @@ else
     build_dir_setup_enabled=false
 fi
 
-if $build_dir_setup_enabled && [ -z "$MACHINE" ];then
-    usage
-    echo -e "ERROR: You must set MACHINE when creating a new build directory."
-    clean_up
-    return 1
-fi
+if $build_dir_setup_enabled;then
+    if [ -z "$MACHINE" ];then
+        usage
+        echo -e "ERROR: You must set MACHINE when creating a new build directory."
+        clean_up
+        return 1
+    fi
+    if [ -z "$DISTRO" ]; then
+        usage
+        echo -e "ERROR: You must set DISTRO when creating a new build directory."
+        clean_up
+        return 1
+    fi
 
-# Check the machine type specified
-LIST_MACHINES=`ls -1 $CWD/layers/*/conf/machine`
-VALID_MACHINE=`echo -e "$LIST_MACHINES" | grep ${MACHINE}.conf$ | wc -l`
-if [ "$MACHINE" = "" ] || [ "$VALID_MACHINE" = "0" ]; then
-    echo -e "\nThe \$MACHINE you have specified ($MACHINE) is not supported by this build setup"
-    usage && clean_up
-    return 1
-fi
-if [ ! -e $TEMPLATECONF/local.conf.sample ]; then
-    echo "Configuring for ${MACHINE}"
+    # Check the machine type specified
+    LIST_MACHINES=`find layers/ -path '*/conf/machine/*.conf'`
+    VALID_MACHINE=`echo "$LIST_MACHINES" | grep "/${MACHINE}.conf$" | wc -l`
+    if [ "$MACHINE" = "" ] || [ "$VALID_MACHINE" = "0" ]; then
+        echo -e "\nThe \$MACHINE you have specified ($MACHINE) is not supported by this build setup"
+        usage && clean_up
+        return 1
+    fi
+    if [ ! -e "$1/conf/local.conf.sample" ]; then
+        echo "Configuring for ${MACHINE}"
+    fi
+
+    shopt -q nullglob && nullglob=false || nullglob=true
+    $nullglob && shopt -s nullglob
+    distro_dirs="`find layers -path "*/conf/distro/${DISTRO}.conf" -printf "%h\n"`"
+    if [ -z "$distro_dirs" ];then
+        echo "Unsupported distro: '$DISTRO'" >&2
+        usage && clean_up
+        return 1
+    fi
+    bitbake_target=""
+    for d in $distro_dirs;do
+        dir="`dirname "${d}"`/../recipes-core/images"
+        [ -d "$dir" ] || continue
+        distro_images="`cd "$dir" && ls *.bb`"
+        bitbake_target="${bitbake_target} ${distro_images//.bb/ }"
+    done
+    for t in $bitbake_target;do
+        if [ "${t/-image/}" = "${DISTRO}" ];then
+            bitbake_target="$t"
+            break
+        fi
+        if [ "$DISTRO" = "karo-wayland" ];then
+            bitbake_target="karo-image-weston karo-image-mulitmedia"
+        fi
+    done
 fi
 
 if [ -z "$SDKMACHINE" ]; then
     SDKMACHINE=`uname -m`
 fi
-
-if [ -z "$DISTRO" ]; then
-    DISTRO="karo-minimal"
-fi
-shopt -q nullglob && nullglob=false || nullglob=true
-$nullglob && shopt -s nullglob
-distro_dirs="`find layers -path "*/conf/distro/${DISTRO}.conf" -printf "%h\n"`"
-if [ -z "$distro_dirs" ];then
-    echo "Unsupported distro: '$DISTRO'" >&2
-    usage && clean_up
-    return 1
-fi
-bitbake_target=""
-for d in $distro_dirs;do
-    dir="`dirname "${d}"`/../recipes-core/images"
-    [ -d "$dir" ] || continue
-    distro_images="`cd "$dir" && ls *.bb`"
-    bitbake_target="${bitbake_target} ${distro_images//.bb/ }"
-done
-for t in $bitbake_target;do
-    if [ "${t/-image/}" = "${DISTRO}" ];then
-        bitbake_target="$t"
-        break
-    elif [ "${DISTRO}" = "karo-wayland" ];then
-        bitbake_target="karo-image-weston karo-image-qt5"
-        break;
-    fi
-done
 
 OEROOT=$PWD/layers/poky
 if [ -e $PWD/layers/oe-core ]; then
@@ -196,7 +200,7 @@ if $updated; then
     return
 fi
 
-. $OEROOT/oe-init-build-env $CWD/$1 > /dev/null
+. "$OEROOT/oe-init-build-env" "$CWD/$1" > /dev/null
 
 # if conf/local.conf not generated, no need to go further
 if [ ! -e conf/local.conf ]; then
@@ -247,14 +251,14 @@ reference manual which can be found at:
 For more information about OpenEmbedded see their website:
     https://www.openembedded.org/
 
-For Ka-Ro specific documentation please refer to:
-    "Getting Started" > "Documentation" in the products page on
+For a Ka-Ro specific Yocto guide please refer to:
+    "Getting Started" > "Yocto Guide" in the respective TX module page on
     https://www.karo-electronics.com
-
-You can start your build now with:
+${bitbake_target:+\
+You can start your build now with:\
 $(for i in ${bitbake_target:-core-image-minimal};do \
-    echo "    bitbake $i"; \
-done )
+    echo -ne "\n    bitbake $i"; \
+done )}
 
 EOF
 
