rework with Linux 4.13 + 4.14.24

diff --git a/base/setup-environment b/base/setup-environment
--- a/base/setup-environment
+++ b/base/setup-environment
@@ -19,33 +19,42 @@
 #
 # Add options for the script
 # Copyright (C) 2013 Freescale Semiconductor, Inc.
-
 CWD=`pwd`
-PROGNAME="setup-environment"
+PROGNAME=setup-environment
 
 usage()
 {
     echo -e "\nUsage: source $PROGNAME <build-dir>
     <build-dir>: specifies the build directory location (required)
 
-If undefined, this script will set \$MACHINE to 'imx6qsabresd'.
+If undefined, this script will set \$MACHINE to 'imx6q-tx6-emmc'.
 "
 
-    ls sources/*/conf/machine/*.conf > /dev/null 2>&1
-    if [ $? -eq 0 ]; then
+    shopt -s nullglob
+    for s in sources/*/conf/machine/*.conf;do
         echo -e "
-Supported machines: `echo; ls sources/*/conf/machine/*.conf \
-| sed s/\.conf//g | sed -r 's/^.+\///' | xargs -I% echo -e "\t%"`
+Supported machines: `echo; ls sources/*/conf/machine/*.conf | \
+sed 's/^.*\//\t/;s/\.conf//'`
+
+Supported distros: `echo; grep -h '^DISTRO_NAME ' sources/*/conf/distro/*.conf | \
+sed 's/^.*= "/\t/;s/"//'`
 
 To build for a machine listed above, run this script as:
-MACHINE=<machine> source $PROGNAME <build-dir>
+DISTRO=<distro> MACHINE=<machine> source $PROGNAME <build-dir>
 "
-    fi
+        return
+    done
+	cat << EOF
+No machine configuration files found!
+Make sure, to set up your yocto source directory with:
+    repo init -u git@github.com:karo-electronics/karo-manifest -b master
+    repo sync
+EOF
 }
 
 clean_up()
 {
-   unset EULA LIST_MACHINES VALID_MACHINE
+   unset LIST_MACHINES VALID_MACHINE
    unset CWD TEMPLATES SHORTOPTS LONGOPTS ARGS PROGNAME
    unset generated_config updated
    unset MACHINE SDKMACHINE DISTRO OEROOT
@@ -64,8 +73,7 @@ if [ $? != 0 -o $# -lt 1 ]; then
 fi
 
 eval set -- "$ARGS"
-while true;
-do
+while true;do
     case $1 in
         -h|--help)
            usage
@@ -80,17 +88,18 @@ do
 done
 
 if [ "$(whoami)" = "root" ]; then
-    echo "ERROR: do not use the BSP as root. Exiting..."
+    echo "ERROR: do not use yocto as root! Exiting..."
+    return 1
 fi
 
 if [ -z "$MACHINE" ]; then
-    MACHINE='imx6qsabresd'
+    MACHINE='imx6q-tx6-emmc'
 fi
 
 # Check the machine type specified
 LIST_MACHINES=`ls -1 $CWD/sources/*/conf/machine`
 VALID_MACHINE=`echo -e "$LIST_MACHINES" | grep ${MACHINE}.conf$ | wc -l`
-if [ "x$MACHINE" = "x" ] || [ "$VALID_MACHINE" = "0" ]; then
+if [ "$MACHINE" = "" ] || [ "$VALID_MACHINE" = "0" ]; then
     echo -e "\nThe \$MACHINE you have specified ($MACHINE) is not supported by this build setup"
     usage && clean_up
     return 1
@@ -101,11 +110,45 @@ else
 fi
 
 if [ -z "$SDKMACHINE" ]; then
-    SDKMACHINE='i686'
+    SDKMACHINE=`uname -m`
 fi
 
 if [ -z "$DISTRO" ]; then
-    DISTRO='poky'
+    case $MACHINE in
+        imx*-tx*)
+            DISTRO="karo-minimal"
+            DEV_MANAGER="busybox-mdev"
+            bitbake_target=karo-image-minimal
+            ;;
+        tx*)
+            DISTRO="poky"
+            bitbake_target=u-boot
+            ;;
+        *)
+            echo "Internal error: Unsupported \$MACHINE: '$MACHINE'"
+            clean_up
+            return 1
+    esac
+else
+    case $DISTRO in
+        karo-minimal)
+            bitbake_target="karo-image-minimal"
+            DEV_MANAGER="busybox-mdev"
+            ;;
+        karo-base|karo-x11)
+            bitbake_target="karo-image${DISTRO#karo}"
+            DEV_MANAGER="udev"
+            ;;
+        uboot|u-boot|u-boot-karo)
+            bitbake_target="u-boot-karo"
+            DISTRO="poky"
+            ;;
+        *)
+            echo "Unsupported distro: '$DISTRO'" >&2
+            usage && clean_up
+            return 1
+            ;;
+    esac
 fi
 
 OEROOT=$PWD/sources/poky
@@ -148,20 +191,22 @@ if [ ! -e conf/local.conf.sample ]; then
     mv conf/local.conf conf/local.conf.sample
 
     # Generate the local.conf based on the Yocto defaults
-    TEMPLATES=$CWD/sources/meta-karo/base/conf 
+    TEMPLATES=$CWD/sources/meta-karo/base/conf
     grep -v '^#\|^$' conf/local.conf.sample > conf/local.conf
-    cat >> conf/local.conf <<EOF
-
-DL_DIR ?= "\${BSPDIR}/downloads/"
-EOF
+#    if [ -n "$DEV_MANAGER" ];then
+#        echo "VIRTUAL-RUNTIME_dev_manager = \"$DEV_MANAGER\"" >> conf/local.conf
+#    fi
+    if [ "$DISTRO" = "karo-minimal" ];then
+        echo 'EXTRA_IMAGE_FEATURES += "read-only-rootfs"' >> conf/local.conf
+    fi
     # Change settings according environment
     sed -e "s,MACHINE ??=.*,MACHINE ??= '$MACHINE',g" \
         -e "s,SDKMACHINE ??=.*,SDKMACHINE ??= '$SDKMACHINE',g" \
         -e "s,DISTRO ?=.*,DISTRO ?= '$DISTRO',g" \
+        -e "s,POKY_DISTRO ?=.*,POKY_DISTRO ?= '$POKY_DISTRO',g" \
         -i conf/local.conf
 
     cp $TEMPLATES/* conf/
-
     for s in $HOME/.oe $HOME/.yocto; do
         if [ -e $s/site.conf ]; then
             echo "Linking $s/site.conf to conf/site.conf"
@@ -172,77 +217,22 @@ EOF
     generated_config=1
 fi
 
-# Handle EULA setting
-EULA_ACCEPTED=
-
-# EULA has been accepted already (ACCEPT_FSL_EULA is set in local.conf)
-if grep -q '^\s*ACCEPT_FSL_EULA\s*=\s*["'\'']..*["'\'']' conf/local.conf; then
-    EULA_ACCEPTED=1
-fi
-
-if [ -z "$EULA_ACCEPTED" ] && [ -n "$EULA" ]; then
-    # The FSL EULA is not set as accepted in local.conf, but the EULA
-    # variable is set in the environment, so we just configure
-    # ACCEPT_FSL_EULA in local.conf according to $EULA.
-    echo "ACCEPT_FSL_EULA = \"$EULA\"" >> conf/local.conf
-elif [ -n "$EULA_ACCEPTED" ]; then
-    # The FSL EULA has been accepted once, so ACCEPT_FSL_EULA is set
-    # in local.conf.  No need to do anything.
-    :
-else
-    # THE FSL EULA is not set as accepted in local.conf, and EULA is
-    # not set in the environment, so we need to ask user if he/she
-    # accepts the FSL EULA:
-    cat <<EOF
-
-Some BSPs depend on libraries and packages which are covered by Freescale's
-End User License Agreement (EULA). To have the right to use these binaries in
-your images, you need to read and accept the following...
-
-EOF
-
-    sleep 4
-
-    more -d $CWD/sources/meta-fsl-arm/EULA
-    echo
-    REPLY=
-    while [ -z "$REPLY" ]; do
-        echo -n "Do you accept the EULA you just read? (y/n) "
-        read REPLY
-        case "$REPLY" in
-            y|Y)
-            echo "EULA has been accepted."
-            echo "ACCEPT_FSL_EULA = \"1\"" >> conf/local.conf
-            ;;
-            n|N)
-            echo "EULA has not been accepted."
-            ;;
-            *)
-            REPLY=
-            ;;
-        esac
-    done
-fi
-
 cat <<EOF
 
-Welcome to Freescale Community BSP
+Welcome to Ka-Ro electronics TX module BSP
 
 The Yocto Project has extensive documentation about OE including a
 reference manual which can be found at:
-    http://yoctoproject.org/documentation
+    https://yoctoproject.org/documentation
 
 For more information about OpenEmbedded see their website:
-    http://www.openembedded.org/
+    https://www.openembedded.org/
 
-You can now run 'bitbake <target>'
+For a Ka-Ro specific Yocto guide please refer to:
+    "Getting Started" > "Yocto Guide" in the respective TX module page on
+    https://www.karo-electronics.com
 
-Common targets are:
-    core-image-minimal
-    meta-toolchain
-    meta-toolchain-sdk
-    adt-installer
-    meta-ide-support
+You can start your build now with 'bitbake $bitbake_target'
 
 EOF
 
@@ -253,7 +243,6 @@ Your build environment has been configured with:
     MACHINE=$MACHINE
     SDKMACHINE=$SDKMACHINE
     DISTRO=$DISTRO
-    EULA=$EULA
 EOF
 else
     echo "Your configuration files at $1 have not been touched."
